# syntax=docker/dockerfile:1
FROM golang:1.26-alpine

# Set build arguments
ARG APP_DIR

WORKDIR /app

# Install git for potential dependency fetching
RUN go env -w GOPROXY=https://proxy.golang.org,direct
RUN apk add --no-cache git curl

# The source code will be mounted as a volume in docker-compose
# We just need to ensure we are in the correct service directory

CMD ["go", "run", "cmd/main.go"]
