// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: billing/billing.proto

package billing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBillingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VehicleId     uint32                 `protobuf:"varint,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	ExpenseCost   float64                `protobuf:"fixed64,3,opt,name=expense_cost,json=expenseCost,proto3" json:"expense_cost,omitempty"`
	AdvanceIncome float64                `protobuf:"fixed64,4,opt,name=advance_income,json=advanceIncome,proto3" json:"advance_income,omitempty"`
	TotalExpenses float64                `protobuf:"fixed64,5,opt,name=total_expenses,json=totalExpenses,proto3" json:"total_expenses,omitempty"`
	TotalAdvance  float64                `protobuf:"fixed64,6,opt,name=total_advance,json=totalAdvance,proto3" json:"total_advance,omitempty"`
	Balance       float64                `protobuf:"fixed64,7,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBillingRequest) Reset() {
	*x = CreateBillingRequest{}
	mi := &file_billing_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBillingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillingRequest) ProtoMessage() {}

func (x *CreateBillingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillingRequest.ProtoReflect.Descriptor instead.
func (*CreateBillingRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBillingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateBillingRequest) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *CreateBillingRequest) GetExpenseCost() float64 {
	if x != nil {
		return x.ExpenseCost
	}
	return 0
}

func (x *CreateBillingRequest) GetAdvanceIncome() float64 {
	if x != nil {
		return x.AdvanceIncome
	}
	return 0
}

func (x *CreateBillingRequest) GetTotalExpenses() float64 {
	if x != nil {
		return x.TotalExpenses
	}
	return 0
}

func (x *CreateBillingRequest) GetTotalAdvance() float64 {
	if x != nil {
		return x.TotalAdvance
	}
	return 0
}

func (x *CreateBillingRequest) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type CreateBillingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBillingResponse) Reset() {
	*x = CreateBillingResponse{}
	mi := &file_billing_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBillingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillingResponse) ProtoMessage() {}

func (x *CreateBillingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillingResponse.ProtoReflect.Descriptor instead.
func (*CreateBillingResponse) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBillingResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_billing_billing_proto protoreflect.FileDescriptor

const file_billing_billing_proto_rawDesc = "" +
	"\n" +
	"\x15billing/billing.proto\x12\abilling\"\xf5\x01\n" +
	"\x14CreateBillingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\rR\tvehicleId\x12!\n" +
	"\fexpense_cost\x18\x03 \x01(\x01R\vexpenseCost\x12%\n" +
	"\x0eadvance_income\x18\x04 \x01(\x01R\radvanceIncome\x12%\n" +
	"\x0etotal_expenses\x18\x05 \x01(\x01R\rtotalExpenses\x12#\n" +
	"\rtotal_advance\x18\x06 \x01(\x01R\ftotalAdvance\x12\x18\n" +
	"\abalance\x18\a \x01(\x01R\abalance\"'\n" +
	"\x15CreateBillingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2`\n" +
	"\x0eBillingService\x12N\n" +
	"\rCreateBilling\x12\x1d.billing.CreateBillingRequest\x1a\x1e.billing.CreateBillingResponseB*Z(github.com/makabas/shared/pkg/pb/billingb\x06proto3"

var (
	file_billing_billing_proto_rawDescOnce sync.Once
	file_billing_billing_proto_rawDescData []byte
)

func file_billing_billing_proto_rawDescGZIP() []byte {
	file_billing_billing_proto_rawDescOnce.Do(func() {
		file_billing_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_billing_proto_rawDesc), len(file_billing_billing_proto_rawDesc)))
	})
	return file_billing_billing_proto_rawDescData
}

var file_billing_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_billing_billing_proto_goTypes = []any{
	(*CreateBillingRequest)(nil),  // 0: billing.CreateBillingRequest
	(*CreateBillingResponse)(nil), // 1: billing.CreateBillingResponse
}
var file_billing_billing_proto_depIdxs = []int32{
	0, // 0: billing.BillingService.CreateBilling:input_type -> billing.CreateBillingRequest
	1, // 1: billing.BillingService.CreateBilling:output_type -> billing.CreateBillingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_billing_billing_proto_init() }
func file_billing_billing_proto_init() {
	if File_billing_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_billing_proto_rawDesc), len(file_billing_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_billing_proto_goTypes,
		DependencyIndexes: file_billing_billing_proto_depIdxs,
		MessageInfos:      file_billing_billing_proto_msgTypes,
	}.Build()
	File_billing_billing_proto = out.File
	file_billing_billing_proto_goTypes = nil
	file_billing_billing_proto_depIdxs = nil
}
