// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: billing/billing.proto

package billing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Expense struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expense) Reset() {
	*x = Expense{}
	mi := &file_billing_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expense) ProtoMessage() {}

func (x *Expense) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expense.ProtoReflect.Descriptor instead.
func (*Expense) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{0}
}

func (x *Expense) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Expense) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Expense) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Expense) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Advance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Advance) Reset() {
	*x = Advance{}
	mi := &file_billing_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Advance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Advance) ProtoMessage() {}

func (x *Advance) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Advance.ProtoReflect.Descriptor instead.
func (*Advance) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{1}
}

func (x *Advance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Advance) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Advance) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Advance) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Billing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VehicleId     uint32                 `protobuf:"varint,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Expenses      []*Expense             `protobuf:"bytes,3,rep,name=expenses,proto3" json:"expenses,omitempty"`
	Advances      []*Advance             `protobuf:"bytes,4,rep,name=advances,proto3" json:"advances,omitempty"`
	TotalExpenses float64                `protobuf:"fixed64,5,opt,name=total_expenses,json=totalExpenses,proto3" json:"total_expenses,omitempty"`
	TotalAdvances float64                `protobuf:"fixed64,6,opt,name=total_advances,json=totalAdvances,proto3" json:"total_advances,omitempty"`
	BalanceDue    float64                `protobuf:"fixed64,7,opt,name=balance_due,json=balanceDue,proto3" json:"balance_due,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Billing) Reset() {
	*x = Billing{}
	mi := &file_billing_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Billing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Billing) ProtoMessage() {}

func (x *Billing) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Billing.ProtoReflect.Descriptor instead.
func (*Billing) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{2}
}

func (x *Billing) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Billing) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *Billing) GetExpenses() []*Expense {
	if x != nil {
		return x.Expenses
	}
	return nil
}

func (x *Billing) GetAdvances() []*Advance {
	if x != nil {
		return x.Advances
	}
	return nil
}

func (x *Billing) GetTotalExpenses() float64 {
	if x != nil {
		return x.TotalExpenses
	}
	return 0
}

func (x *Billing) GetTotalAdvances() float64 {
	if x != nil {
		return x.TotalAdvances
	}
	return 0
}

func (x *Billing) GetBalanceDue() float64 {
	if x != nil {
		return x.BalanceDue
	}
	return 0
}

func (x *Billing) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Billing) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetBillingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     uint32                 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingRequest) Reset() {
	*x = GetBillingRequest{}
	mi := &file_billing_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingRequest) ProtoMessage() {}

func (x *GetBillingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingRequest.ProtoReflect.Descriptor instead.
func (*GetBillingRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{3}
}

func (x *GetBillingRequest) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

type CreateBillingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     uint32                 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBillingRequest) Reset() {
	*x = CreateBillingRequest{}
	mi := &file_billing_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBillingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillingRequest) ProtoMessage() {}

func (x *CreateBillingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillingRequest.ProtoReflect.Descriptor instead.
func (*CreateBillingRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBillingRequest) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

type AddExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     uint32                 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddExpenseRequest) Reset() {
	*x = AddExpenseRequest{}
	mi := &file_billing_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddExpenseRequest) ProtoMessage() {}

func (x *AddExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddExpenseRequest.ProtoReflect.Descriptor instead.
func (*AddExpenseRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{5}
}

func (x *AddExpenseRequest) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *AddExpenseRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *AddExpenseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddExpenseRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AddAdvanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     uint32                 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAdvanceRequest) Reset() {
	*x = AddAdvanceRequest{}
	mi := &file_billing_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAdvanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAdvanceRequest) ProtoMessage() {}

func (x *AddAdvanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAdvanceRequest.ProtoReflect.Descriptor instead.
func (*AddAdvanceRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{6}
}

func (x *AddAdvanceRequest) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *AddAdvanceRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *AddAdvanceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddAdvanceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DeleteBillingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     uint32                 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBillingRequest) Reset() {
	*x = DeleteBillingRequest{}
	mi := &file_billing_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBillingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBillingRequest) ProtoMessage() {}

func (x *DeleteBillingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBillingRequest.ProtoReflect.Descriptor instead.
func (*DeleteBillingRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBillingRequest) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_billing_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_billing_billing_proto protoreflect.FileDescriptor

const file_billing_billing_proto_rawDesc = "" +
	"\n" +
	"\x15billing/billing.proto\x12\abilling\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n" +
	"\aExpense\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\"g\n" +
	"\aAdvance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\"\xc1\x02\n" +
	"\aBilling\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\rR\tvehicleId\x12,\n" +
	"\bexpenses\x18\x03 \x03(\v2\x10.billing.ExpenseR\bexpenses\x12,\n" +
	"\badvances\x18\x04 \x03(\v2\x10.billing.AdvanceR\badvances\x12%\n" +
	"\x0etotal_expenses\x18\x05 \x01(\x01R\rtotalExpenses\x12%\n" +
	"\x0etotal_advances\x18\x06 \x01(\x01R\rtotalAdvances\x12\x1f\n" +
	"\vbalance_due\x18\a \x01(\x01R\n" +
	"balanceDue\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"2\n" +
	"\x11GetBillingRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\rR\tvehicleId\"5\n" +
	"\x14CreateBillingRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\rR\tvehicleId\"\x80\x01\n" +
	"\x11AddExpenseRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\rR\tvehicleId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\"\x80\x01\n" +
	"\x11AddAdvanceRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\rR\tvehicleId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\"5\n" +
	"\x14DeleteBillingRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\rR\tvehicleId\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xcf\x02\n" +
	"\x0eBillingService\x12:\n" +
	"\n" +
	"GetBilling\x12\x1a.billing.GetBillingRequest\x1a\x10.billing.Billing\x12@\n" +
	"\rCreateBilling\x12\x1d.billing.CreateBillingRequest\x1a\x10.billing.Billing\x12:\n" +
	"\n" +
	"AddExpense\x12\x1a.billing.AddExpenseRequest\x1a\x10.billing.Billing\x12:\n" +
	"\n" +
	"AddAdvance\x12\x1a.billing.AddAdvanceRequest\x1a\x10.billing.Billing\x12G\n" +
	"\rDeleteBilling\x12\x1d.billing.DeleteBillingRequest\x1a\x17.billing.DeleteResponseB*Z(github.com/makabas/shared/pkg/pb/billingb\x06proto3"

var (
	file_billing_billing_proto_rawDescOnce sync.Once
	file_billing_billing_proto_rawDescData []byte
)

func file_billing_billing_proto_rawDescGZIP() []byte {
	file_billing_billing_proto_rawDescOnce.Do(func() {
		file_billing_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_billing_proto_rawDesc), len(file_billing_billing_proto_rawDesc)))
	})
	return file_billing_billing_proto_rawDescData
}

var file_billing_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_billing_billing_proto_goTypes = []any{
	(*Expense)(nil),              // 0: billing.Expense
	(*Advance)(nil),              // 1: billing.Advance
	(*Billing)(nil),              // 2: billing.Billing
	(*GetBillingRequest)(nil),    // 3: billing.GetBillingRequest
	(*CreateBillingRequest)(nil), // 4: billing.CreateBillingRequest
	(*AddExpenseRequest)(nil),    // 5: billing.AddExpenseRequest
	(*AddAdvanceRequest)(nil),    // 6: billing.AddAdvanceRequest
	(*DeleteBillingRequest)(nil), // 7: billing.DeleteBillingRequest
	(*DeleteResponse)(nil),       // 8: billing.DeleteResponse
}
var file_billing_billing_proto_depIdxs = []int32{
	0, // 0: billing.Billing.expenses:type_name -> billing.Expense
	1, // 1: billing.Billing.advances:type_name -> billing.Advance
	3, // 2: billing.BillingService.GetBilling:input_type -> billing.GetBillingRequest
	4, // 3: billing.BillingService.CreateBilling:input_type -> billing.CreateBillingRequest
	5, // 4: billing.BillingService.AddExpense:input_type -> billing.AddExpenseRequest
	6, // 5: billing.BillingService.AddAdvance:input_type -> billing.AddAdvanceRequest
	7, // 6: billing.BillingService.DeleteBilling:input_type -> billing.DeleteBillingRequest
	2, // 7: billing.BillingService.GetBilling:output_type -> billing.Billing
	2, // 8: billing.BillingService.CreateBilling:output_type -> billing.Billing
	2, // 9: billing.BillingService.AddExpense:output_type -> billing.Billing
	2, // 10: billing.BillingService.AddAdvance:output_type -> billing.Billing
	8, // 11: billing.BillingService.DeleteBilling:output_type -> billing.DeleteResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_billing_billing_proto_init() }
func file_billing_billing_proto_init() {
	if File_billing_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_billing_proto_rawDesc), len(file_billing_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_billing_proto_goTypes,
		DependencyIndexes: file_billing_billing_proto_depIdxs,
		MessageInfos:      file_billing_billing_proto_msgTypes,
	}.Build()
	File_billing_billing_proto = out.File
	file_billing_billing_proto_goTypes = nil
	file_billing_billing_proto_depIdxs = nil
}
