// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: billing/billing.proto

package billing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillingService_GetBilling_FullMethodName    = "/billing.BillingService/GetBilling"
	BillingService_CreateBilling_FullMethodName = "/billing.BillingService/CreateBilling"
	BillingService_AddExpense_FullMethodName    = "/billing.BillingService/AddExpense"
	BillingService_AddAdvance_FullMethodName    = "/billing.BillingService/AddAdvance"
	BillingService_DeleteBilling_FullMethodName = "/billing.BillingService/DeleteBilling"
)

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillingServiceClient interface {
	GetBilling(ctx context.Context, in *GetBillingRequest, opts ...grpc.CallOption) (*Billing, error)
	CreateBilling(ctx context.Context, in *CreateBillingRequest, opts ...grpc.CallOption) (*Billing, error)
	AddExpense(ctx context.Context, in *AddExpenseRequest, opts ...grpc.CallOption) (*Billing, error)
	AddAdvance(ctx context.Context, in *AddAdvanceRequest, opts ...grpc.CallOption) (*Billing, error)
	DeleteBilling(ctx context.Context, in *DeleteBillingRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) GetBilling(ctx context.Context, in *GetBillingRequest, opts ...grpc.CallOption) (*Billing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Billing)
	err := c.cc.Invoke(ctx, BillingService_GetBilling_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CreateBilling(ctx context.Context, in *CreateBillingRequest, opts ...grpc.CallOption) (*Billing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Billing)
	err := c.cc.Invoke(ctx, BillingService_CreateBilling_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) AddExpense(ctx context.Context, in *AddExpenseRequest, opts ...grpc.CallOption) (*Billing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Billing)
	err := c.cc.Invoke(ctx, BillingService_AddExpense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) AddAdvance(ctx context.Context, in *AddAdvanceRequest, opts ...grpc.CallOption) (*Billing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Billing)
	err := c.cc.Invoke(ctx, BillingService_AddAdvance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) DeleteBilling(ctx context.Context, in *DeleteBillingRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, BillingService_DeleteBilling_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
// All implementations must embed UnimplementedBillingServiceServer
// for forward compatibility.
type BillingServiceServer interface {
	GetBilling(context.Context, *GetBillingRequest) (*Billing, error)
	CreateBilling(context.Context, *CreateBillingRequest) (*Billing, error)
	AddExpense(context.Context, *AddExpenseRequest) (*Billing, error)
	AddAdvance(context.Context, *AddAdvanceRequest) (*Billing, error)
	DeleteBilling(context.Context, *DeleteBillingRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedBillingServiceServer()
}

// UnimplementedBillingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServiceServer struct{}

func (UnimplementedBillingServiceServer) GetBilling(context.Context, *GetBillingRequest) (*Billing, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBilling not implemented")
}
func (UnimplementedBillingServiceServer) CreateBilling(context.Context, *CreateBillingRequest) (*Billing, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBilling not implemented")
}
func (UnimplementedBillingServiceServer) AddExpense(context.Context, *AddExpenseRequest) (*Billing, error) {
	return nil, status.Error(codes.Unimplemented, "method AddExpense not implemented")
}
func (UnimplementedBillingServiceServer) AddAdvance(context.Context, *AddAdvanceRequest) (*Billing, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAdvance not implemented")
}
func (UnimplementedBillingServiceServer) DeleteBilling(context.Context, *DeleteBillingRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBilling not implemented")
}
func (UnimplementedBillingServiceServer) mustEmbedUnimplementedBillingServiceServer() {}
func (UnimplementedBillingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBillingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServiceServer will
// result in compilation errors.
type UnsafeBillingServiceServer interface {
	mustEmbedUnimplementedBillingServiceServer()
}

func RegisterBillingServiceServer(s grpc.ServiceRegistrar, srv BillingServiceServer) {
	// If the following call panics, it indicates UnimplementedBillingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingService_ServiceDesc, srv)
}

func _BillingService_GetBilling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBillingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetBilling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetBilling_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetBilling(ctx, req.(*GetBillingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CreateBilling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBillingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CreateBilling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CreateBilling_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CreateBilling(ctx, req.(*CreateBillingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_AddExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddExpenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).AddExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_AddExpense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).AddExpense(ctx, req.(*AddExpenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_AddAdvance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAdvanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).AddAdvance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_AddAdvance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).AddAdvance(ctx, req.(*AddAdvanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_DeleteBilling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBillingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).DeleteBilling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_DeleteBilling_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).DeleteBilling(ctx, req.(*DeleteBillingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingService_ServiceDesc is the grpc.ServiceDesc for BillingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBilling",
			Handler:    _BillingService_GetBilling_Handler,
		},
		{
			MethodName: "CreateBilling",
			Handler:    _BillingService_CreateBilling_Handler,
		},
		{
			MethodName: "AddExpense",
			Handler:    _BillingService_AddExpense_Handler,
		},
		{
			MethodName: "AddAdvance",
			Handler:    _BillingService_AddAdvance_Handler,
		},
		{
			MethodName: "DeleteBilling",
			Handler:    _BillingService_DeleteBilling_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing/billing.proto",
}
